//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faith.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faith.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTBASE_DESCRIPTION.
        /// </summary>
        public static string BOTBASE_DESCRIPTION {
            get {
                return ResourceManager.GetString("BOTBASE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/4Y5HSjP.
        /// </summary>
        public static string BOTBASE_DISCORD {
            get {
                return ResourceManager.GetString("BOTBASE_DISCORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTBASE_NAME.
        /// </summary>
        public static string BOTBASE_NAME {
            get {
                return ResourceManager.GetString("BOTBASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/TheManta/Faith.
        /// </summary>
        public static string BOTBASE_URL {
            get {
                return ResourceManager.GetString("BOTBASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BEHAVIOR_ENTERED.
        /// </summary>
        public static string LOG_BEHAVIOR_ENTERED {
            get {
                return ResourceManager.GetString("LOG_BEHAVIOR_ENTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BEHAVIOR_EXITED_HANDLED.
        /// </summary>
        public static string LOG_BEHAVIOR_EXITED_HANDLED {
            get {
                return ResourceManager.GetString("LOG_BEHAVIOR_EXITED_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BEHAVIOR_EXITED_UNHANDLED.
        /// </summary>
        public static string LOG_BEHAVIOR_EXITED_UNHANDLED {
            get {
                return ResourceManager.GetString("LOG_BEHAVIOR_EXITED_UNHANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BEHAVIOR_LIST_COMPLETE.
        /// </summary>
        public static string LOG_BEHAVIOR_LIST_COMPLETE {
            get {
                return ResourceManager.GetString("LOG_BEHAVIOR_LIST_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BOTBASE_FINISHED.
        /// </summary>
        public static string LOG_BOTBASE_FINISHED {
            get {
                return ResourceManager.GetString("LOG_BOTBASE_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BOTBASE_STARTED.
        /// </summary>
        public static string LOG_BOTBASE_STARTED {
            get {
                return ResourceManager.GetString("LOG_BOTBASE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_BOTBASE_STOPPED.
        /// </summary>
        public static string LOG_BOTBASE_STOPPED {
            get {
                return ResourceManager.GetString("LOG_BOTBASE_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_CUTSCENE_SKIPPING.
        /// </summary>
        public static string LOG_CUTSCENE_SKIPPING {
            get {
                return ResourceManager.GetString("LOG_CUTSCENE_SKIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_DUTY_COMMENCED.
        /// </summary>
        public static string LOG_DUTY_COMMENCED {
            get {
                return ResourceManager.GetString("LOG_DUTY_COMMENCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_LOCALIZATION_CHANGED.
        /// </summary>
        public static string LOG_LOCALIZATION_CHANGED {
            get {
                return ResourceManager.GetString("LOG_LOCALIZATION_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load localization &quot;{cultureCode}&quot;: resource file not found..
        /// </summary>
        public static string LOG_LOCALIZATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_LOCALIZATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_SETTINGS_CLICKED.
        /// </summary>
        public static string LOG_SETTINGS_CLICKED {
            get {
                return ResourceManager.GetString("LOG_SETTINGS_CLICKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_SETTINGS_NEW_WINDOW.
        /// </summary>
        public static string LOG_SETTINGS_NEW_WINDOW {
            get {
                return ResourceManager.GetString("LOG_SETTINGS_NEW_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_SETTINGS_TO_TOP.
        /// </summary>
        public static string LOG_SETTINGS_WINDOW_TO_TOP {
            get {
                return ResourceManager.GetString("LOG_SETTINGS_WINDOW_TO_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS_CUTSCENE_WAIT.
        /// </summary>
        public static string STATUS_CUTSCENE_WAIT {
            get {
                return ResourceManager.GetString("STATUS_CUTSCENE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS_DUTY_WAIT_COMMENCED.
        /// </summary>
        public static string STATUS_DUTY_WAIT_COMMENCED {
            get {
                return ResourceManager.GetString("STATUS_DUTY_WAIT_COMMENCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS_LOADING_WAIT.
        /// </summary>
        public static string STATUS_LOADING_WAIT {
            get {
                return ResourceManager.GetString("STATUS_LOADING_WAIT", resourceCulture);
            }
        }
    }
}
